export const books = [
  { name: "Gênesis", alternatives: ["Gn", "Genesis", "Gen"] },
  { name: "Êxodo", alternatives: ["Ex", "Exodus", "Exo"] },
  { name: "Levítico", alternatives: ["Lv", "Leviticus", "Lev"] },
  { name: "Números", alternatives: ["Nm", "Numbers", "Num"] },
  { name: "Deuteronômio", alternatives: ["Dt", "Deuteronomy", "Deut"] },
  { name: "Josué", alternatives: ["Js", "Joshua", "Josh"] },
  { name: "Juízes", alternatives: ["Jz", "Judges", "Jud"] },
  { name: "Rute", alternatives: ["Rt", "Ruth", "Ruth"] },
  { name: "1 Samuel", alternatives: ["1 Sm", "1 Samuel", "1 Sam"] },
  { name: "2 Samuel", alternatives: ["2 Sm", "2 Samuel", "2 Sam"] },
  { name: "1 Reis", alternatives: ["1 Rs", "1 Kings", "1 Kgs"] },
  { name: "2 Reis", alternatives: ["2 Rs", "2 Kings", "2 Kgs"] },
  { name: "1 Crônicas", alternatives: ["1 Cr", "1 Chronicles", "1 Chr"] },
  { name: "2 Crônicas", alternatives: ["2 Cr", "2 Chronicles", "2 Chr"] },
  { name: "Esdras", alternatives: ["Ed", "Ezra", "Ezra"] },
  { name: "Neemias", alternatives: ["Ne", "Nehemiah", "Neh"] },
  { name: "Ester", alternatives: ["Est", "Esther", "Esth"] },
  { name: "Jó", alternatives: ["Jo", "Job", "Job"] },
  { name: "Salmos", alternatives: ["Sl", "Psalms", "Ps"] },
  { name: "Provérbios", alternatives: ["Pv", "Proverbs", "Prov"] },
  { name: "Eclesiastes", alternatives: ["Ec", "Ecclesiastes", "Eccl"] },
  { name: "Cânticos", alternatives: ["Ct", "Song of Solomon", "Song"] },
  { name: "Isaías", alternatives: ["Is", "Isaiah", "Isa"] },
  { name: "Jeremias", alternatives: ["Jer", "Jeremiah", "Jer"] },
  { name: "Lamentações", alternatives: ["Lm", "Lamentations", "Lam"] },
  { name: "Ezequiel", alternatives: ["Ez", "Ezekiel", "Ezek"] },
  { name: "Daniel", alternatives: ["Dn", "Daniel", "Dan"] },
  { name: "Oséias", alternatives: ["Os", "Hosea", "Hos"] },
  { name: "Joel", alternatives: ["Jl", "Joel", "Joel"] },
  { name: "Amós", alternatives: ["Am", "Amos", "Amos"] },
  { name: "Obadias", alternatives: ["Ob", "Obadiah", "Obad"] },
  { name: "Jonas", alternatives: ["Jn", "Jonah", "Jon"] },
  { name: "Miquéias", alternatives: ["Mq", "Micah", "Mic"] },
  { name: "Naum", alternatives: ["Na", "Nahum", "Nah"] },
  { name: "Habacuque", alternatives: ["Hab", "Habakkuk", "Hab"] },
  { name: "Sofonias", alternatives: ["Sf", "Zephaniah", "Zeph"] },
  { name: "Ageu", alternatives: ["Ag", "Haggai", "Hag"] },
  { name: "Zacarias", alternatives: ["Zc", "Zechariah", "Zech"] },
  { name: "Malaquias", alternatives: ["Ml", "Malachi", "Mal"] },
  { name: "Mateus", alternatives: ["Mt", "Matthew", "Matt"] },
  { name: "Marcos", alternatives: ["Mc", "Mark", "Mk"] },
  { name: "Lucas", alternatives: ["Lc", "Luke", "Lk"] },
  { name: "João", alternatives: ["Jo", "John", "Jn"] },
  { name: "Atos", alternatives: ["At", "Acts", "Acts"] },
  { name: "Romanos", alternatives: ["Rm", "Romans", "Rom"] },
  { name: "1 Coríntios", alternatives: ["1 Co", "1 Corinthians", "1 Cor"] },
  { name: "2 Coríntios", alternatives: ["2 Co", "2 Corinthians", "2 Cor"] },
  { name: "Gálatas", alternatives: ["Gl", "Galatians", "Gal"] },
  { name: "Efésios", alternatives: ["Ef", "Ephesians", "Eph"] },
  { name: "Filipenses", alternatives: ["Fp", "Philippians", "Phil"] },
  { name: "Colossenses", alternatives: ["Cl", "Colossians", "Col"] },
  { name: "1 Tessalonicenses", alternatives: ["1 Ts", "1 Thessalonians", "1 Thess"] },
  { name: "2 Tessalonicenses", alternatives: ["2 Ts", "2 Thessalonians", "2 Thess"] },
  { name: "1 Timóteo", alternatives: ["1 Tm", "1 Timothy", "1 Tim"] },
  { name: "2 Timóteo", alternatives: ["2 Tm", "2 Timothy", "2 Tim"] },
  { name: "Tito", alternatives: ["Tt", "Titus", "Tit"] },
  { name: "Filemom", alternatives: ["Fm", "Philemon", "Phm"] },
  { name: "Hebreus", alternatives: ["Hb", "Hebrews", "Heb"] },
  { name: "Tiago", alternatives: ["Tg", "James", "Jam"] },
  { name: "1 Pedro", alternatives: ["1 Pe", "1 Peter", "1 Pet"] },
  { name: "2 Pedro", alternatives: ["2 Pe", "2 Peter", "2 Pet"] },
  { name: "1 João", alternatives: ["1 Jo", "1 John", "1 Jn"] },
  { name: "2 João", alternatives: ["2 Jo", "2 John", "2 Jn"] },
  { name: "3 João", alternatives: ["3 Jo", "3 John", "3 Jn"] },
  { name: "Judas", alternatives: ["Jd", "Jude", "Jude"] },
  { name: "Apocalipse", alternatives: ["Ap", "Revelation", "Rev"] }

] as const satisfies { name: string; alternatives: string[] }[];

export type BookName = (typeof books)[number]['name'];

