export const books = [
  { name: "Gênesis", abbreviation: "Gn" },
  { name: "Êxodo", abbreviation: "Ex" },
  { name: "Levítico", abbreviation: "Lv" },
  { name: "Números", abbreviation: "Nm" },
  { name: "Deuteronômio", abbreviation: "Dt" },
  { name: "Josué", abbreviation: "Js" },
  { name: "Juízes", abbreviation: "Jz" },
  { name: "Rute", abbreviation: "Rt" },
  { name: "1 Samuel", abbreviation: "1 Sm" },
  { name: "2 Samuel", abbreviation: "2 Sm" },
  { name: "1 Reis", abbreviation: "1 Rs" },
  { name: "2 Reis", abbreviation: "2 Rs" },
  { name: "1 Crônicas", abbreviation: "1 Cr" },
  { name: "2 Crônicas", abbreviation: "2 Cr" },
  { name: "Esdras", abbreviation: "Ed" },
  { name: "Neemias", abbreviation: "Ne" },
  { name: "Ester", abbreviation: "Est" },
  { name: "Jó", abbreviation: "Jo" },
  { name: "Salmos", abbreviation: "Sl" },
  { name: "Provérbios", abbreviation: "Pv" },
  { name: "Eclesiastes", abbreviation: "Ec" },
  { name: "Cânticos", abbreviation: "Ct" },
  { name: "Isaías", abbreviation: "Is" },
  { name: "Jeremias", abbreviation: "Jer" },
  { name: "Lamentações", abbreviation: "Lm" },
  { name: "Ezequiel", abbreviation: "Ez" },
  { name: "Daniel", abbreviation: "Dn" },
  { name: "Oséias", abbreviation: "Os" },
  { name: "Joel", abbreviation: "Jl" },
  { name: "Amós", abbreviation: "Am" },
  { name: "Obadias", abbreviation: "Ob" },
  { name: "Jonas", abbreviation: "Jn" },
  { name: "Miquéias", abbreviation: "Mq" },
  { name: "Naum", abbreviation: "Na" },
  { name: "Habacuque", abbreviation: "Hab" },
  { name: "Sofonias", abbreviation: "Sf" },
  { name: "Ageu", abbreviation: "Ag" },
  { name: "Zacarias", abbreviation: "Zc" },
  { name: "Malaquias", abbreviation: "Ml" },
  { name: "Mateus", abbreviation: "Mt" },
  { name: "Marcos", abbreviation: "Mc" },
  { name: "Lucas", abbreviation: "Lc" },
  { name: "João", abbreviation: "Jo" },
  { name: "Atos", abbreviation: "At" },
  { name: "Romanos", abbreviation: "Rm" },
  { name: "1 Coríntios", abbreviation: "1 Co" },
  { name: "2 Coríntios", abbreviation: "2 Co" },
  { name: "Gálatas", abbreviation: "Gl" },
  { name: "Efésios", abbreviation: "Ef" },
  { name: "Filipenses", abbreviation: "Fp" },
  { name: "Colossenses", abbreviation: "Cl" },
  { name: "1 Tessalonicenses", abbreviation: "1 Ts" },
  { name: "2 Tessalonicenses", abbreviation: "2 Ts" },
  { name: "1 Timóteo", abbreviation: "1 Tm" },
  { name: "2 Timóteo", abbreviation: "2 Tm" },
  { name: "Tito", abbreviation: "Tt" },
  { name: "Filemom", abbreviation: "Fm" },
  { name: "Hebreus", abbreviation: "Hb" },
  { name: "Tiago", abbreviation: "Tg" },
  { name: "1 Pedro", abbreviation: "1 Pe" },
  { name: "2 Pedro", abbreviation: "2 Pe" },
  { name: "1 João", abbreviation: "1 Jo" },
  { name: "2 João", abbreviation: "2 Jo" },
  { name: "3 João", abbreviation: "3 Jo" },
  { name: "Judas", abbreviation: "Jd" },
  { name: "Apocalipse", abbreviation: "Ap" },
] as const satisfies { name: string; abbreviation: string }[];

export type BookName = (typeof books)[number]['name'];

